### ISSUE TITLE
vim mode error

### ISSUE THREAD

**Issue by Gavlooth** [lem-project/lem#583]
I get the following error after installing lem with ros 
and enabling git mode
![image](https://user-images.githubusercontent.com/10321050/173190358-3eb0400d-c0e1-416f-a979-16dc24f0f2f2.png)

**Comment by Gavlooth** [comment]
The same problem when compiling lem from source

**Comment by cxxxr** [comment]
What is git mode?
Perhaps the extension is the cause of the error.

**Comment by Gavlooth** [comment]
> 

I mis-wrote, I ment vi-mode

**Comment by cxxxr** [comment]
Fixed in [this commit](https://github.com/lem-project/lem/commit/c63ab71a04a65db948b2b8c2c31aeff1fdd156a6).

**Comment by cxxxr** [comment]
I believe I have fixed this problem.
Thank you for the report.
I'll close the issue once, but let me know if you still have problems.

**Comment by Gavlooth** [comment]
The problem persists. 
I compiled from both master and your commit, no luck

**Comment by Gavlooth** [comment]
![image](https://user-images.githubusercontent.com/10321050/173196368-e333954b-310b-453c-a240-91805728f712.png)

**Comment by Gavlooth** [comment]
this is my init.lisp 
;; -*- mode:lisp -*-

(in-package :lem-user)

(push "~/.local/lem-pareto/" asdf:*central-registry*)

(asdf:load-system :lem-pareto)
;; Enable Paredit and Pareto along with Lisp mode
(add-hook *find-file-hook*
          (lambda (buffer)
            (when (eq (buffer-major-mode buffer)
                      'lem-lisp-mode:lisp-mode)
              (change-buffer-mode buffer 'lem-paredit-mode:paredit-mode t)
              (change-buffer-mode buffer 'lem-pareto-mode:pareto-mode t))))


 ;; -*- mode:lisp -*-

;;; copy to $HOME/.lemrc


;;(load-theme "emacs-light")


(load-theme "monokai")

(setf *scroll-recenter-p* t)
(setf (variable-value 'line-wrap :global) nil)
(setf (variable-value 'lem.line-numbers:line-numbers :global) t)

;;; vi-mode

(lem-vi-mode:vi-mode)
 
;; General
(define-key lem:*global-keymap* "Space f f" 'lem:find-file)
(define-key lem:*global-keymap* "Space b b" 'lem:switch-to-buffer)

;; VI
; (define-key lem-vi-mode:*command-keymap* "q"  'quit-window)

(define-key lem-vi-mode:*command-keymap* "q" 'quit-active-window)
(define-key lem-vi-mode:*insert-keymap* "C-n" 'lem.abbrev:abbrev-with-pop-up-window)
(define-key lem-vi-mode:*insert-keymap* "j k" 'lem-vi-mode.commands:vi-end-insert)

;; CL
(define-key lem-lisp-mode:*lisp-mode-keymap* "Space e e" 'lem-lisp-mode:lisp-eval-last-expression)
(define-key lem-lisp-mode:*lisp-mode-keymap* "Space e f" 'lem-lisp-mode:lisp-load-file)

**Comment by cxxxr** [comment]
I can't say for sure, but the version may not have been updated.
Could you please tell me how you compiled master and tried it?

**Comment by Gavlooth** [comment]
Bootstrap, configure , make , make install I prefer to avoid Roswell as I am not really using it

**Comment by cxxxr** [comment]
What does the `M-x `lem-version` command output? (Logs can be found in the *Message* buffer)

If the latest status is not reflected
- What about deleting the ~/.cache/common-lisp directory and reinstalling?
- Does it reproduce if I put it in vi-mode after starting without init.lisp?

**Comment by Gavlooth** [comment]
![image](https://user-images.githubusercontent.com/10321050/173220107-0afc0932-9de0-435e-b85d-33618249acf8.png)

**Comment by Gavlooth** [comment]
![image](https://user-images.githubusercontent.com/10321050/173220125-9d283eee-e224-4aa6-91c2-2a49815857af.png)

**Comment by cxxxr** [comment]
Looks like a revision prior to c63ab71a04a65db948b2b8c2c31aeff1fdd156a6.
Please try git pull and make again.

**Comment by Gavlooth** [comment]
Deleting the cache folder fixed the problem, but i think this is also a bug

**Comment by cxxxr** [comment]
In any case, it seems that the cause of the error is that lem has not been updated in your environment.
- Make sure the cloned repository is up to date.
- Make sure make, make install was successful.
