### ISSUE TITLE
Lem for NixOS?

### ISSUE THREAD

**Issue by Ashvith10** [lem-project/lem#890]
I've tried making Lem work on NixOS using both `roswell` and `sbcl`, but I'm not well-versed in either of Nix and Common Lisp. Here's my attempt at creating a derivation:

```nix
{
  pkgs ? import <nixpkgs> {},
  stdenv ? pkgs.stdenv,
  fetchFromGitHub ? pkgs.fetchFromGitHub,
  sbcl' ? pkgs.sbcl.withPackages (ps: with ps; [
    alexandria
  ])
}:
stdenv.mkDerivation rec {
  pname = "lem";
  version = "2.1.0";

  src = fetchFromGitHub {
    owner = "lem-project";
    repo = pname;
    rev = "v${version}";
    sha256 = "1bjm6z33n1ksjvqs5v1g1mz4f8bsx1lka85sspmlnsbswwap58k0";
  };

  buildInputs = [
    sbcl'
  ];

  buildPhase = ''
  ${sbcl'}/bin/sbcl --eval '(ql:quickload :lem-ncurses)' --load build.lisp
  '';

  # TODO: Complete later
  installPhase = ''
  '';
}
```

Here's what I get when I try building this locally:
```sh
$ nix-build 
this derivation will be built:
  /nix/store/spd8x1w7m7wbqv31flzq0am0gr0wfd8w-lem-2.1.0.drv
building '/nix/store/spd8x1w7m7wbqv31flzq0am0gr0wfd8w-lem-2.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/8f87spmw4pbi40cvlnh788p4zny6mibg-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
This is SBCL 2.3.4.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD tid=31 "main thread" RUNNING {1001088003}>:
  Package QL does not exist.

    Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(ql:quic...">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE ] Use the current package, COMMON-LISP-USER.
  1: [RETRY    ] Retry finding the package.
  2: [USE-VALUE] Specify a different package
  3: [UNINTERN ] Read the symbol as uninterned.
  4: [SYMBOL   ] Specify a symbol to return
  5:             Ignore runtime option --eval "(ql:quickload :lem-ncurses)".
  6: [ABORT    ] Skip rest of --eval and --load options.
  7:             Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT     ] Exit SBCL (calling #'EXIT, killing the process).

(SB-IMPL::READER-FIND-PACKAGE "QL" #<SB-IMPL::STRING-INPUT-STREAM {7FFFF788F8B3}> T)
0] 
* @nix { "action": "setPhase", "phase": "installPhase" }
installing
install flags: SHELL=/nix/store/8fv91097mbh5049i9rglc73dx6kjg3qk-bash-5.2-p15/bin/bash install
make: *** No rule to make target 'install'.  Stop.
error: builder for '/nix/store/spd8x1w7m7wbqv31flzq0am0gr0wfd8w-lem-2.1.0.drv' failed with exit code 2;
       last 10 log lines:
       >   6: [ABORT    ] Skip rest of --eval and --load options.
       >   7:             Skip to toplevel READ/EVAL/PRINT loop.
       >   8: [EXIT     ] Exit SBCL (calling #'EXIT, killing the process).
       >
       > (SB-IMPL::READER-FIND-PACKAGE "QL" #<SB-IMPL::STRING-INPUT-STREAM {7FFFF788F8B3}> T)
       > 0]
       > * @nix { "action": "setPhase", "phase": "installPhase" }
       > installing
       > install flags: SHELL=/nix/store/8fv91097mbh5049i9rglc73dx6kjg3qk-bash-5.2-p15/bin/bash install
       > make: *** No rule to make target 'install'.  Stop.
       For full logs, run 'nix log /nix/store/spd8x1w7m7wbqv31flzq0am0gr0wfd8w-lem-2.1.0.drv'.
```

**Comment by Neshamon** [comment]
Quicklisp is something that needs to be installed separately

**Comment by Ashvith10** [comment]
@Neshamon can you share the build command? I'm not sure why the Makefile exists, because the README.md file gives a different instruction on building. I am interested in targeting the CLI build.

**Comment by Sasanidas** [comment]
I think there is not yet a build command for Quicklisp, the installation still have to be carried manually or I guess with a script (https://www.quicklisp.org/beta/#installation)

**Comment by Sasanidas** [comment]
Instead of evaluating directly in the command line, you can use the Make commands https://lem-project.github.io/lem-page/installation/getting-started/#with-make

**Comment by Sasanidas** [comment]
Sorry about the README documentation, the webpage should reflect more recent (and hopefully accurate) the current state of the project.

**Comment by Ashvith10** [comment]
@Sasanidas quicklisp installation fails every time I try the `nix-build` command.
```sh
$ nix log /nix/store/2c6bl18r636cqi0axv4lkp4nfipmhwyf-lem-2.1.0.drv | cat
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/8f87spmw4pbi40cvlnh788p4zny6mibg-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
This is SBCL 2.3.4.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

  ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

WARNING: Making .quicklisp part of the install pathname directory
Unhandled SB-BSD-SOCKETS:TRY-AGAIN-ERROR in thread #<SB-THREAD:THREAD tid=20 "main thread" RUNNING
                                                      {1004430113}>:
  Name service error in "getaddrinfo": -3 (Temporary failure in name resolution)

Backtrace for: #<SB-THREAD:THREAD tid=20 "main thread" RUNNING {1004430113}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-BSD-SOCKETS:TRY-AGAIN-ERROR {1002337EB3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-BSD-SOCKETS:TRY-AGAIN-ERROR {1002337EB3}>)
2: (INVOKE-DEBUGGER #<SB-BSD-SOCKETS:TRY-AGAIN-ERROR {1002337EB3}>)
3: (ERROR SB-BSD-SOCKETS:TRY-AGAIN-ERROR :ERRNO -3 :SYSCALL "getaddrinfo")
4: (SB-BSD-SOCKETS:NAME-SERVICE-ERROR "getaddrinfo" -3)
5: (SB-BSD-SOCKETS:GET-HOST-BY-NAME #<unavailable argument>)
6: ((:METHOD QLQS-NETWORK::%OPEN-CONNECTION (QLQS-IMPL:SBCL T T)) #<QLQS-IMPL:SBCL {10045A76A3}> "beta.quicklisp.org" 80) [fast-method]
7: ((:METHOD QLQS-NETWORK::%CALL-WITH-CONNECTION (T T T T)) #<QLQS-IMPL:SBCL {10045A76A3}> "beta.quicklisp.org" 80 #<FUNCTION (LAMBDA (QLQS-HTTP::CONNECTION) :IN QLQS-HTTP:FETCH) {10021EC6BB}>) [fast-method]
8: (QLQS-HTTP:FETCH #<QLQS-HTTP::URL "http://beta.quicklisp.org/client/quicklisp.sexp"> #P"/nix/store/049fnr0p7gknz8s6fp26d4z0igzlin3x-lem-2.1.0/.quicklisp/tmp/fetch.dat" :FOLLOW-REDIRECTS T :QUIETLY NIL :MAXIMUM-REDIRECTS NIL)
9: (QUICKLISP-QUICKSTART::RENAMING-FETCH "http://beta.quicklisp.org/client/quicklisp.sexp" #P"/nix/store/049fnr0p7gknz8s6fp26d4z0igzlin3x-lem-2.1.0/.quicklisp/tmp/client-info.sexp")
10: (QUICKLISP-QUICKSTART::FETCH-CLIENT-INFO-PLIST "http://beta.quicklisp.org/client/quicklisp.sexp")
11: (QUICKLISP-QUICKSTART::FETCH-CLIENT-INFO "http://beta.quicklisp.org/client/quicklisp.sexp")
12: (QUICKLISP-QUICKSTART::INITIAL-INSTALL :CLIENT-URL "http://beta.quicklisp.org/client/quicklisp.sexp" :DIST-URL NIL)
13: ((:METHOD QLQS-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<QLQS-IMPL:SBCL {10045A76A3}> #<FUNCTION (LAMBDA NIL :IN QUICKLISP-QUICKSTART:INSTALL) {1002163FAB}>) [fast-method]
14: ((:METHOD QLQS-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QLQS-IMPL:SBCL T)) #<QLQS-IMPL:SBCL {10045A76A3}> #<FUNCTION (LAMBDA NIL :IN QUICKLISP-QUICKSTART:INSTALL) {1002163FAB}>) [fast-method]
15: (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/049fnr0p7gknz8s6fp26d4z0igzlin3x-lem-2.1.0/.quicklisp" :PROXY NIL :CLIENT-URL NIL :CLIENT-VERSION NIL :DIST-URL NIL :DIST-VERSION NIL)
16: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/049fnr0p7gknz8s6fp26d4z0igzlin3x-lem-2.1.0/.quicklisp") #<NULL-LEXENV>)
17: (EVAL (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/049fnr0p7gknz8s6fp26d4z0igzlin3x-lem-2.1.0/.quicklisp"))
18: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "/nix/store/f8fdihg8vk27py68hb1n0srpc9km5iv8-quicklisp.lisp") (:EVAL . "(quicklisp-quickstart:install :path \"/nix/store/049fnr0p7gknz8s6fp26d4z0igzlin3x-lem-2.1.0/.quicklisp\")") (:QUIT)))
19: (SB-IMPL::TOPLEVEL-INIT)
20: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
21: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
22: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Sasanidas** [comment]
That's kind of an odd error, which command are you launching? Keep in mind that with the sbcl --load command it will trigger the interactive REPL, so maybe a script to trigger the quicklisp options and then exit

**Comment by Ashvith10** [comment]
@Sasanidas I've modified the Nix files a little bit, but the problem still persists. I'll share the file and the build failure logs below, just to make sure:
```nix
{
  pkgs ? import <nixpkgs> {},
  stdenv ? pkgs.stdenv,
  fetchurl ? pkgs.fetchurl,
  fetchFromGitHub ? pkgs.fetchFromGitHub,
  ncurses ? pkgs.ncurses,
  sbcl ? pkgs.sbcl,
  make ? pkgs.gnumake,
  tree ? pkgs.tree
}:
stdenv.mkDerivation rec {
  pname = "lem";
  version = "2.1.0";

  src = fetchFromGitHub {
    owner = "lem-project";
    repo = pname;
    rev = "v${version}";
    sha256 = "1bjm6z33n1ksjvqs5v1g1mz4f8bsx1lka85sspmlnsbswwap58k0";
  };

  quickLisp = fetchurl {
    url = "https://beta.quicklisp.org/quicklisp.lisp";
    sha256 = "05rcxg7rrkp925s155p0rk848jp2jxrjcm3q0hbn8wg0xcm5qyja";
  };

  buildInputs = [
    ncurses
    tree
    make
  ];
  
  configurePhase = ''
    export HOME=$out
    export QUICKLISP_DIR=$out/.quicklisp;
    ${sbcl}/bin/sbcl \
      --non-interactive \
      --no-userinit \
      --load "${quickLisp}" \
      --eval "(quicklisp-quickstart:install :path \"$QUICKLISP_DIR\")" \
      --eval "(ql(ql:add-to-init-file))" \
      --eval "(quit)"
    '';

  buildPhase = ''
  tree | grep @
  '';

  installPhase = ''
  tree | grep @
  '';
}
```

```sh
$ nix-build 
this derivation will be built:
  /nix/store/ncjdq871588dil8wp8sxjg6cxxyrrgk5-lem-2.1.0.drv
building '/nix/store/ncjdq871588dil8wp8sxjg6cxxyrrgk5-lem-2.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/8f87spmw4pbi40cvlnh788p4zny6mibg-source
source root is source
patching sources
configuring
This is SBCL 2.3.4.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

  ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

WARNING: Making .quicklisp part of the install pathname directory
Unhandled SB-BSD-SOCKETS:TRY-AGAIN-ERROR in thread #<SB-THREAD:THREAD tid=20 "main thread" RUNNING
                                                      {1004430113}>:
  Name service error in "getaddrinfo": -3 (Temporary failure in name resolution)

Backtrace for: #<SB-THREAD:THREAD tid=20 "main thread" RUNNING {1004430113}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-BSD-SOCKETS:TRY-AGAIN-ERROR {100233CFC3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-BSD-SOCKETS:TRY-AGAIN-ERROR {100233CFC3}>)
2: (INVOKE-DEBUGGER #<SB-BSD-SOCKETS:TRY-AGAIN-ERROR {100233CFC3}>)
3: (ERROR SB-BSD-SOCKETS:TRY-AGAIN-ERROR :ERRNO -3 :SYSCALL "getaddrinfo")
4: (SB-BSD-SOCKETS:NAME-SERVICE-ERROR "getaddrinfo" -3)
5: (SB-BSD-SOCKETS:GET-HOST-BY-NAME #<unavailable argument>)
6: ((:METHOD QLQS-NETWORK::%OPEN-CONNECTION (QLQS-IMPL:SBCL T T)) #<QLQS-IMPL:SBCL {10045917C3}> "beta.quicklisp.org" 80) [fast-method]
7: ((:METHOD QLQS-NETWORK::%CALL-WITH-CONNECTION (T T T T)) #<QLQS-IMPL:SBCL {10045917C3}> "beta.quicklisp.org" 80 #<FUNCTION (LAMBDA (QLQS-HTTP::CONNECTION) :IN QLQS-HTTP:FETCH) {10021E972B}>) [fast-method]
8: (QLQS-HTTP:FETCH #<QLQS-HTTP::URL "http://beta.quicklisp.org/client/quicklisp.sexp"> #P"/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp/tmp/fetch.dat" :FOLLOW-REDIRECTS T :QUIETLY NIL :MAXIMUM-REDIRECTS NIL)
9: (QUICKLISP-QUICKSTART::RENAMING-FETCH "http://beta.quicklisp.org/client/quicklisp.sexp" #P"/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp/tmp/client-info.sexp")
10: (QUICKLISP-QUICKSTART::FETCH-CLIENT-INFO-PLIST "http://beta.quicklisp.org/client/quicklisp.sexp")
11: (QUICKLISP-QUICKSTART::FETCH-CLIENT-INFO "http://beta.quicklisp.org/client/quicklisp.sexp")
12: (QUICKLISP-QUICKSTART::INITIAL-INSTALL :CLIENT-URL "http://beta.quicklisp.org/client/quicklisp.sexp" :DIST-URL NIL)
13: ((:METHOD QLQS-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<QLQS-IMPL:SBCL {10045917C3}> #<FUNCTION (LAMBDA NIL :IN QUICKLISP-QUICKSTART:INSTALL) {10021612AB}>) [fast-method]
14: ((:METHOD QLQS-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QLQS-IMPL:SBCL T)) #<QLQS-IMPL:SBCL {10045917C3}> #<FUNCTION (LAMBDA NIL :IN QUICKLISP-QUICKSTART:INSTALL) {10021612AB}>) [fast-method]
15: (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp" :PROXY NIL :CLIENT-URL NIL :CLIENT-VERSION NIL :DIST-URL NIL :DIST-VERSION NIL)
16: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp") #<NULL-LEXENV>)
17: (EVAL (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp"))
18: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "/nix/store/f8fdihg8vk27py68hb1n0srpc9km5iv8-quicklisp.lisp") (:EVAL . "(quicklisp-quickstart:install :path \"/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp\")") (:EVAL . "(ql(ql:add-to-init-file))") (:EVAL . "(quit)") (:QUIT)))
19: (SB-IMPL::TOPLEVEL-INIT)
20: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
21: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
22: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
error: builder for '/nix/store/ncjdq871588dil8wp8sxjg6cxxyrrgk5-lem-2.1.0.drv' failed with exit code 1;
       last 10 log lines:
       > 15: (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp" :PROXY NIL :CLIENT-URL NIL :CLIENT-VERSION NIL :DIST-URL NIL :DIST-VERSION NIL)
       > 16: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp") #<NULL-LEXENV>)
       > 17: (EVAL (QUICKLISP-QUICKSTART:INSTALL :PATH "/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp"))
       > 18: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "/nix/store/f8fdihg8vk27py68hb1n0srpc9km5iv8-quicklisp.lisp") (:EVAL . "(quicklisp-quickstart:install :path \"/nix/store/v5ms8k7vidkanskcc43wa9f6m8wli4j4-lem-2.1.0/.quicklisp\")") (:EVAL . "(ql(ql:add-to-init-file))") (:EVAL . "(quit)") (:QUIT)))
       > 19: (SB-IMPL::TOPLEVEL-INIT)
       > 20: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
       > 21: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
       > 22: (SB-IMPL::%START-LISP)
       >
       > unhandled condition in --disable-debugger mode, quitting
       For full logs, run 'nix log /nix/store/ncjdq871588dil8wp8sxjg6cxxyrrgk5-lem-2.1.0.drv'.

```

**Comment by Sasanidas** [comment]
Seems like it maybe a path problem that quicklisp is trying to use, maybe use something like https://github.com/SquircleSpace/ql2nix

**Comment by Sasanidas** [comment]
It's using some tricks to get quicklisp installed, maybe that approach works https://github.com/SquircleSpace/ql2nix/blob/master/nixlispBundle.nix#L52

**Comment by Ashvith10** [comment]
@Sasanidas Here's after toying around a bit more, I was able to move pass the Quicklisp issue without having to use `ql2nix`, but I have to deal with this issue now:
```
$ nix log /nix/store/7iv7lh5h847iffxd2ppya9f05hf7pagm-nsb-cga-20200427-git.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/x118r80mfv8rxk0nk479s240qn0h33b9-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
This is SBCL 2.3.4.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* #<PACKAGE "NIX-CL-USER">
* #<PACKAGE "NIX-CL-USER">
* T
* LOAD-SYSTEMS
* BUILD FAILED: Component #:SB-CGA not found, required by #<SYSTEM "nsb-cga">

```

**Comment by Ashvith10** [comment]
Looks like there's some issue with [lisp-modules](https://nixos.org/manual/nixpkgs/stable/#lisp) - and that has to do with quicklisp and not the modules themselves. I've created an issue [here](NixOS/nixpkgs#248034), and hopefully, it should fix the issue with SB-CGA.

**Comment by Ashvith10** [comment]
@Sasanidas Looks like most of the issues have been dealt with. Right now, the following lines are causing problems while trying to build Lem on NixOS:

https://github.com/lem-project/lem/blob/bfb29bca384340b094f6c75f9e3176812d5245bd/scripts/patch.lisp#L1

https://github.com/lem-project/lem/blob/bfb29bca384340b094f6c75f9e3176812d5245bd/scripts/patch-build-ncurses.lisp#L3

https://github.com/lem-project/lem/blob/bfb29bca384340b094f6c75f9e3176812d5245bd/scripts/patch-build-sdl2.lisp#L3

(I've not tested with SDL2, but obviously, it will cause an issue, as lisp-modules does not use QuickLisp)

Is it possible to remove these lines, so that we can install them outside using `--eval`?

This is the log, by the way:
```sh
$ NIXPKGS=~/Desktop/nixpkgs/ && nix-build $NIXPKGS -A lem
this derivation will be built:
  /nix/store/8cgdsiiyz6375g75zvfz41qrxnnm7mrl-lem-2.1.0.drv
building '/nix/store/8cgdsiiyz6375g75zvfz41qrxnnm7mrl-lem-2.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/8f87spmw4pbi40cvlnh788p4zny6mibg-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
This is SBCL 2.3.7.nixos, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
While evaluating the form starting at line 1, column 0
  of #P"/build/source/scripts/patch-build-ncurses.lisp":

debugger invoked on a SB-C::INPUT-ERROR-IN-LOAD in thread
#<THREAD tid=35 "main thread" RUNNING {1001098003}>:
  READ error during LOAD:

    Package QL does not exist.

      Line: 1, Column: 13, File-Position: 12

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /build/source/scripts/patch.lisp" {10010EB373}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT   ] Abort loading file "/build/source/scripts/patch.lisp".
  1: [RETRY   ] Retry EVAL of current toplevel form.
  2: [CONTINUE] Ignore error and continue loading file "/build/source/scripts/patch-build-ncurses.lisp".
  3:            Abort loading file "/build/source/scripts/patch-build-ncurses.lisp".
  4:            Ignore runtime option --load "scripts/patch-build-ncurses.lisp".
  5:            Skip rest of --eval and --load options.
  6:            Skip to toplevel READ/EVAL/PRINT loop.
  7: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {10010EC523}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /build/source/scripts/patch.lisp" {10010EB373}>)
0] 

debugger invoked on a SB-C::INPUT-ERROR-IN-LOAD in thread
#<THREAD tid=35 "main thread" RUNNING {1001098003}>:
  READ error during LOAD:

    Package QL does not exist.

      Line: 3, Column: 13, File-Position: 41

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /build/source/scripts/patch-build-ncurses.lisp" {10010E9353}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT   ] Abort loading file "/build/source/scripts/patch-build-ncurses.lisp".
  1: [CONTINUE] Ignore runtime option --load "scripts/patch-build-ncurses.lisp".
  2:            Skip rest of --eval and --load options.
  3:            Skip to toplevel READ/EVAL/PRINT loop.
  4: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {10010EF8C3}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /build/source/scripts/patch-build-ncurses.lisp" {10010E9353}>)
0] 
* @nix { "action": "setPhase", "phase": "installPhase" }
installing
TODO: Install phase jobs...
post-installation fixup
error: builder for '/nix/store/8cgdsiiyz6375g75zvfz41qrxnnm7mrl-lem-2.1.0.drv' failed to produce output path for output 'out' at '/nix/store/8cgdsiiyz6375g75zvfz41qrxnnm7mrl-lem-2.1.0.drv.chroot/nix/store/dihz4qizyzmdpbhzkb7h65s2nhqsayp6-lem-2.1.0'
```

 [Here's](https://github.com/NixOS/nixpkgs/compare/master...Ashvith10:nixpkgs:add-lem-to-nixpkgs) the branch I'm going to push to nixpkgs. Speaking of which I think I might have to create two separate packages, right? One for `ncurses` and another for `sdl2`?

**Comment by Sasanidas** [comment]
> Is it possible to remove these lines, so that we can install them outside using --eval?

Seems like the error is still that quicklisp is not properly detected, I'm not sure how the NixOS system works, but keep in mind that SBCL needs to have the quicklisp setup file loaded at the start so it can detect the system, wiht the function `(ql:add-to-init-file)` which what it does is adding a few lines to the user file ~/.sbclrc, these lines:
```
;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))

```

So maybe sbcl is not founding that initial file to load quicklisp, if that's a major issue, quicklisp can still be loaded manually, loading the setup file before everything else (also with the --load keyword of sbcl)



> [Here's](https://github.com/NixOS/nixpkgs/compare/master...Ashvith10:nixpkgs:add-lem-to-nixpkgs) the branch I'm going to push to nixpkgs. Speaking of which I think I might have to create two separate packages, right? One for ncurses and another for sdl2?

Probably, yes, the ncurses versions uses [cl-charms](https://github.com/HiTECNOLOGYs/cl-charms#introduction) for the ncurses wrapper and SDL2 uses the Debian packages defined [here](https://lem-project.github.io/lem-page/installation/sdl2/#install)

**Comment by Sasanidas** [comment]
Quicklisp requires ASDF, which usually ships on the implementation (even tho it's not in the standard).

Thanks for the link, I'll give it a read tomorrow, also thanks for the effort :+1:

**Comment by Ashvith10** [comment]
@Sasanidas looks like it is simply not possible to use Quicklisp inside Nix packages without removing the sandbox. And as stated by [this comment](https://discourse.nixos.org/t/how-do-i-access-internet-inside-nix-build/7671/2), it is considered a bad practice. The only viable option would be to create my own build script, I guess - perhaps stick with ASDF. I've tested with ASDF, and it seems to work fine, but fails at `scripts/patch.lisp` while trying to clone the patches, and says that the domain is unavailable (a hint at sand-boxing blocking all network communication - perhaps the BSD-SOCKET issue before was also caused by this - it simply wouldn't let Quicklisp download it's stuff).

**Comment by Neshamon** [comment]
Sorry I couldn't answer before, got a bit busy. But the `:lem-ncurses` package is the terminal version of Lem, there's also a graphical version called `:lem-sdl2` 

The `build.lisp` file will create a Lem binary so you don't have to build Lem every time you want to run it.

As for `:quick-patch` that seems to be a module downloaded by Quicklisp. I'll have to look more into it to see exactly what it does

**Comment by Ashvith10** [comment]
@Neshamon the `sb-ext` module is missing on Nix pkgs, I might have to ask the maintainer to add this. But about Quickslisp, it is simply not possible to use them in Nixpkgs, at least for now. I don't know what's the equivalent of `import` or `require` in SBCL, but so far, I've been using `asdf:load-system :name-of-package`, and looks like there's some progress in that direction.

**Comment by Sasanidas** [comment]
sb-ext sould be included on the SBCL standard compilation, so you shouldn't worry about it, indeed seems like the major problem is to download the dependencies, maybe a hack-ish workaround can be to download every dependency manually (they are not that much, really, this is not npm) to the ~/quicklisp/local-projects directory.

**Comment by Sasanidas** [comment]
The funciton that dump the image to the executable is https://www.sbcl.org/manual/#Function-sb_002dext-save_002dlisp_002dand_002ddie 

But like I said, the sb-ext package is in the core so it should be available

**Comment by Ashvith10** [comment]
@Sasanidas would you mind taking a look at [this](https://github.com/NixOS/nixpkgs/issues/248132#issuecomment-1686852222) - it looks like we have to be entirely dependent on nixpkgs and not the build script.

**Comment by Sasanidas** [comment]
Interesting, indeed the only ASDF approach may work, but keep in mind the installation script is doing more thing than just quickloading the Lem system, it's also running quickpatch which set some dependencies from it.

I would really like to just use quicklisp for it really, even if quicklisp install other packages (on the location quicklisp/dist), don't know if there is a better solution (or easy) really.

**Comment by dariof4** [comment]
As far as I can tell the quick patch script is only setting `log4cl` and `esrap` to their latest git commits, I don't think it's needed anymore though since quicklisp updated in June and both of those should already be at their latest git commit in quicklisp afaik.

I've got a mostly working flake for `lem-ncurses` (sdl2 could also be done, but it doesn't run on my system due to unrelated issues so I haven't got around to it yet) https://github.com/dariof4/lem-flake/.

Loading contrib systems using the `load-library` command doesn't work, they need to be `(asdf:load-system)`'d in the `default.nix`, also some contrib systems like `calc-mode` would also need to be patched to not use `(ql:quickload)`.

I did it by patching out uses of `(ql:quickload)` with `(asdf:load-system)`, I will admit though that it isn't the most maintainable solution :P (due to having to maintain long lived patches).

I'll also add a link to this https://github.com/NixOS/nixpkgs/issues/250777, where some conversation about packaging lem is going on.
